### ISSUE TITLE
自定义角色前置加载不正确

### ISSUE THREAD

**Issue by fancub** [LXG-Shadow/Arknights-Dolos#1]
![2](https://user-images.githubusercontent.com/75276194/100929341-c872f980-34e7-11eb-893f-c32a25d6371a.PNG)
角色信息倒是能改，其他没效果
![捕获](https://user-images.githubusercontent.com/75276194/100929460-f3f5e400-34e7-11eb-96df-ecabb51aef9f.PNG)

**Comment by fancub** [comment]
要改下路径，是我傻了

**Comment by aynakeya** [comment]
喵？
