### ISSUE TITLE
能设计个GUI吗

### ISSUE THREAD

**Issue by Lynricsy** [LXG-Shadow/Arknights-Dolos#2]
现在怎么修改配置啊（是我不配了）

**Comment by Lynricsy** [comment]
或者在`main.py`里面每个配置项加一个注释也行啊

**Comment by Lynricsy** [comment]
哦对
你可以看一下<a href="https://github.com/likiblaze/ac-updater">LikiBlaze/AC-Updater</a>可以让更新json更容易一些（好奇明明这个这么好写你们这些巨佬为什么不能写一个）

**Comment by Lynricsy** [comment]
”启动网页还是命令行“这个“网页”指的是什么啊

**Comment by aynakeya** [comment]
因为做这个的目的是开发测试，不是为了使用。

1.

修改编队配置建议修改arkhack_troop.json

然后启动时候自定义troopBuilder

```
ArkInterceptor.tBuilder = troopBuilder.init(filepath)
```

当然我提供了一点简单api可供调用，示例代码请看troopEditor.py

```
#初始化
tb = troopBuilder.init()
tb.setCharacterBuilder(characterBuilder.init())

#比如你要添加一个干员
tb.addCharacter("char_103_angel")

#保存编队数据到文件
tb.save()

```

2.

没有所谓的配置项，所有的操作皆由addon的方式实现。

如果你想要自己做一个config来实现你所说的操作也是可以的

具体看main.py中注释掉的示例代码

比如

```
a = userInfo.init("Rua牛","0000",120,0)
master.addons.add(a)
```

3.

json不是开发时必须的，所以更新不更新无所谓的。

你想贡献代码可以通过fork然后pull request。

我建议通过addons的方式实现

4.

意思是启动mitmproxy的方式 使用mitmdump 还是 mitmweb。

使用web是为了抓包方便测试。
