### ISSUE TITLE
编队错误

### ISSUE THREAD

**Issue by fancub** [LXG-Shadow/Arknights-Dolos#3]
![捕获1](https://user-images.githubusercontent.com/75276194/106354298-168e5880-62f1-11eb-9620-071fca6689d6.PNG)
![捕获2](https://user-images.githubusercontent.com/75276194/106354300-19894900-62f1-11eb-9707-f728aae41222.PNG)
新买的号发现改不了编队，是因为阿米娅精二了吗？老的号没练。还有进危机合约是同时看干员原来的等级和所选的技能等级，也就是说只能白嫖潜能。

**Comment by aynakeya** [comment]
是所有账号都出现这个情况嘛? 还是就精2阿米娅的?
我手里没有精2阿米娅的账号，没法复现。
是不是升变导致的？
危机合约有单独的sign检测，中间人攻击实现不了。

我的建议是，去掉所有的addons。单纯抓包看一下squadFormation里数据的样子。然后对比一下哪里出错了。

欢迎fork+pull request.

**Comment by fancub** [comment]
我两个号各抓了一下，麻烦你看看
[squadFormation.zip](https://github.com/LXG-Shadow/Arknights-Dolos/files/5899934/squadFormation.zip)

**Comment by aynakeya** [comment]
无精2的是可以的吧？
如果是的话，
我估计是升变的原因。

**Comment by fancub** [comment]
ok,那这号我就慢慢玩吧

**Comment by aynakeya** [comment]
我的意思是，可以话你可以自己写个插件解决这玩意...

**Comment by aynakeya** [comment]
我突然想到了另一个办法，你要不现在更新一下试试。
