### ISSUE TITLE
现在没法进入作战了啊？

### ISSUE THREAD

**Issue by Lynricsy** [LXG-Shadow/Arknights-Dolos#5]
看你把Battle那里面的干员ID改了，应该就是为了解决阿米娅的问题吧？
可是现在没法进入作战了
改回去也不行
用我原来Fork的可以
好久没看了，最近除了那个阿米娅的还改了哪里呀?
看着有8个commit
你现在还能正常使用吗？

**Comment by Lynricsy** [comment]
（顺便问一下，那个虚假抽卡怎么用啊，当时就是没研究出来，用法和抽卡模拟不一样吗？）

**Comment by aynakeya** [comment]
没在维护了，出问题建议自己修改代码，欢迎pull request。

虚假抽卡是测试用的，自己定义response。

**Comment by Thomitics** [comment]
👌

**Comment by Lynricsy** [comment]
> 没在维护了，出问题建议自己修改代码，欢迎pull request。
> 
> 虚假抽卡是测试用的，自己定义response。

👌
